/**
 * Sortable Columns JavaScript Functions (Extracted for Testing)
 *
 * SYNCHRONIZATION REQUIREMENT:
 * These functions mirror the JavaScript code generated by js_core_generator.py
 * (the sortable columns feature). When modifying the sort functions there,
 * update this file to keep them in sync.
 * After changes, verify with: npm test
 */

// ── Internal state (injectable for testing) ──────────────────────────────────

let _problemData = { file_list: [], data: {} };
let _sortState = {};   // { [fileKey]: { column: string|null, direction: 'asc'|'desc'|'none' } }
let _localStorage = null;

export function setMockProblemData(data) {
  _problemData = data;
}

export function setMockLocalStorage(ls) {
  _localStorage = ls;
}

export function setSortState(state) {
  _sortState = state;
}

export function getSortStateSnapshot() {
  return JSON.parse(JSON.stringify(_sortState));
}

export function resetState() {
  _problemData = { file_list: [], data: {} };
  _sortState = {};
  _localStorage = null;
}

// ── getSortValue ──────────────────────────────────────────────────────────────

const DIFFICULTY_ORDER = { Easy: 1, Medium: 2, Hard: 3 };

/**
 * Extracts a comparable sort value from a problem for a given column.
 * Empty/null values always sort last (returns null).
 *
 * @param {Object} problem
 * @param {string} column  - 'difficulty'|'name'|'time_to_solve'|'intermediate_time'|
 *                           'advanced_time'|'top_time'|'solved_date'
 * @returns {number|string|null}
 */
export function getSortValue(problem, column) {
  switch (column) {
    case 'difficulty': {
      const map = { Easy: 1, Medium: 2, Hard: 3 };
      return map[problem.difficulty] != null ? map[problem.difficulty] : null;
    }
    case 'name':
      return problem.name ? problem.name.toLowerCase() : null;
    case 'time_to_solve':
    case 'intermediate_time':
    case 'advanced_time':
    case 'top_time': {
      const v = parseFloat(problem[column]);
      return isNaN(v) ? null : v;
    }
    case 'solved_date': {
      if (!problem.solved_date) return null;
      const d = Date.parse(problem.solved_date);
      return isNaN(d) ? null : d;
    }
    default:
      return null;
  }
}

// ── getSortedProblems ─────────────────────────────────────────────────────────

/**
 * Returns a sorted copy of the problems for a given fileKey.
 * Sort order is determined by the current sortState for that fileKey.
 * If no sort is active (direction 'none' or no state), returns original order.
 *
 * Null/empty values always sort last regardless of direction.
 *
 * @param {string} fileKey
 * @returns {Object[]}
 */
export function getSortedProblems(fileKey) {
  const problems = (_problemData.data[fileKey] || []).slice();
  const state = _sortState[fileKey];
  if (!state || !state.column || state.direction === 'none') {
    return problems;
  }

  const { column, direction } = state;
  const asc = direction === 'asc' ? 1 : -1;

  return problems.sort((a, b) => {
    const va = getSortValue(a, column);
    const vb = getSortValue(b, column);

    if (va === null && vb === null) return 0;
    if (va === null) return 1;
    if (vb === null) return -1;

    if (va < vb) return -1 * asc;
    if (va > vb) return 1 * asc;
    return 0;
  });
}

// ── Sort state cycling ────────────────────────────────────────────────────────

const DIRECTION_CYCLE = { none: 'asc', asc: 'desc', desc: 'none' };

/**
 * Cycles sort direction for a column: none→asc→desc→none.
 * Clicking a different column resets to 'asc'.
 *
 * @param {string} fileKey
 * @param {string} column
 */
export function cycleSortState(fileKey, column) {
  const current = _sortState[fileKey];
  if (!current || current.column !== column || current.direction === 'none') {
    if (current && current.column !== column) {
      _sortState[fileKey] = { column, direction: 'asc' };
    } else {
      const prevDir = current ? current.direction : 'none';
      _sortState[fileKey] = { column, direction: DIRECTION_CYCLE[prevDir] };
    }
  } else {
    _sortState[fileKey] = { column, direction: DIRECTION_CYCLE[current.direction] };
  }
}

// ── localStorage persistence ──────────────────────────────────────────────────

const SORT_STATE_KEY_PREFIX = 'tracker_sort_';

/**
 * Persists sort state for a fileKey to localStorage.
 * @param {string} fileKey
 */
export function saveSortState(fileKey) {
  const ls = _localStorage || (typeof localStorage !== 'undefined' ? localStorage : null);
  if (!ls) return;
  const state = _sortState[fileKey];
  if (!state) return;
  ls.setItem(SORT_STATE_KEY_PREFIX + fileKey, JSON.stringify(state));
}

/**
 * Restores sort state for a fileKey from localStorage.
 * Returns true if state was restored, false otherwise.
 * @param {string} fileKey
 * @returns {boolean}
 */
export function restoreSortState(fileKey) {
  const ls = _localStorage || (typeof localStorage !== 'undefined' ? localStorage : null);
  if (!ls) return false;
  try {
    const raw = ls.getItem(SORT_STATE_KEY_PREFIX + fileKey);
    if (!raw) return false;
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed.column === 'string' && typeof parsed.direction === 'string') {
      _sortState[fileKey] = parsed;
      return true;
    }
    return false;
  } catch (_) {
    return false;
  }
}

// ── initSortHeaders (DOM-dependent, tested via callback injection) ─────────────

/**
 * Attaches click handlers to sort header elements.
 * Headers are provided as an array of { column, element } objects
 * so the function can be tested without a real DOM.
 *
 * @param {string} fileKey
 * @param {Array<{column: string, element: {addEventListener: function, dataset: object}}>} headers
 * @param {function} [onStateChange] - called with (fileKey, column, direction) after each click
 */
export function initSortHeaders(fileKey, headers, onStateChange) {
  for (const { column, element } of headers) {
    element.addEventListener('click', () => {
      cycleSortState(fileKey, column);
      saveSortState(fileKey);
      if (typeof onStateChange === 'function') {
        const state = _sortState[fileKey];
        onStateChange(fileKey, state.column, state.direction);
      }
    });
  }
}
