/**
 * Storage Notification JavaScript Functions (Extracted for Testing)
 * These functions mirror those generated by js_core_generator.py.
 *
 * SYNCHRONIZATION REQUIREMENT:
 * When modifying showStorageToast(), saveToLocalStorage(), loadFromLocalStorage(),
 * or isLocalStorageAvailable() in js_core_generator.py, update this file too.
 * Verify with: npm test
 */

export const TOAST_DISMISS_MS = 5000;

/**
 * isLocalStorageAvailable()
 * Returns true if localStorage is accessible, false otherwise.
 */
export function isLocalStorageAvailable(_localStorage) {
  const ls = _localStorage || (typeof localStorage !== 'undefined' ? localStorage : null);
  if (!ls) return false;
  try {
    const testKey = '__storage_test__';
    ls.setItem(testKey, '1');
    ls.getItem(testKey);
    ls.removeItem(testKey);
    return true;
  } catch (e) {
    return false;
  }
}

/**
 * showStorageToast(message, type, _document, _setTimeout)
 * Creates a toast notification element with .sync-toast CSS class.
 * type: 'warning' | 'error'
 * Removes any existing #storage-toast before creating a new one.
 * Auto-dismisses after TOAST_DISMISS_MS.
 */
export function showStorageToast(message, type, _document, _setTimeout) {
  const doc = _document || (typeof document !== 'undefined' ? document : null);
  const setTO = _setTimeout || (typeof setTimeout !== 'undefined' ? setTimeout : null);

  if (!doc || !doc.body) return null;

  const existing = doc.getElementById('storage-toast');
  if (existing) existing.remove();

  const toast = doc.createElement('div');
  toast.id = 'storage-toast';
  toast.className = 'sync-toast ' + (type === 'error' ? 'sync-toast-error' : 'sync-toast-warning');
  toast.textContent = message;
  doc.body.appendChild(toast);

  if (setTO) {
    setTO(() => {
      if (toast.parentNode) {
        toast.parentNode.removeChild(toast);
      }
    }, TOAST_DISMISS_MS);
  }

  return toast;
}

/**
 * saveToLocalStorage(fileKey, data, _localStorage, _document, _setTimeout)
 * Saves data to localStorage. Shows warning toast on errors.
 */
export function saveToLocalStorage(fileKey, data, _localStorage, _document, _setTimeout) {
  const ls = _localStorage || (typeof localStorage !== 'undefined' ? localStorage : null);
  if (!ls) return;

  try {
    ls.setItem(`tracker_${fileKey}`, JSON.stringify(data));
  } catch (e) {
    showStorageToast(
      'Your progress could not be saved. Consider exporting your data as a backup.',
      'warning',
      _document,
      _setTimeout
    );
  }
}

/**
 * loadFromLocalStorage(fileKey, _localStorage, _document, _setTimeout)
 * Loads data from localStorage. Shows error toast on parse/access errors.
 * Returns parsed data or null.
 */
export function loadFromLocalStorage(fileKey, _localStorage, _document, _setTimeout) {
  const ls = _localStorage || (typeof localStorage !== 'undefined' ? localStorage : null);
  if (!ls) return null;

  const saved = ls.getItem(`tracker_${fileKey}`);
  if (!saved) return null;

  try {
    return JSON.parse(saved);
  } catch (e) {
    showStorageToast(
      'Your saved progress could not be loaded. Data may be corrupted.',
      'error',
      _document,
      _setTimeout
    );
    return null;
  }
}
