/**
 * Urgent Review Filter JavaScript Functions (Extracted for Testing)
 *
 * SYNCHRONIZATION REQUIREMENT:
 * These functions mirror the JavaScript code generated by js_core_generator.py
 * (calculateDaysUntilFlashing, applyUrgentReviewFilter, updateUrgentBtnState).
 * When modifying those functions, update this file to keep them in sync.
 * After changes, verify with: npm test
 */

import {
  calculateAwarenessScore,
  getCommitmentFactor,
  getTierDifficultyMultiplier,
  getSolvedFactor,
  getConfig,
  setMockProblemData as setAwarenessMockData,
  resetConfig,
  setConfig
} from './awareness.js';

// ── Injectable state for testing ─────────────────────────────────────────────

let _problemData = { file_list: [], data: {} };

export function setMockProblemData(data) {
  _problemData = data;
  setAwarenessMockData(data);
}

export function resetState() {
  _problemData = { file_list: [], data: {} };
  setAwarenessMockData({ file_list: [], data: {} });
  resetConfig();
}

export { setConfig, getConfig };

// ── calculateDaysUntilFlashing ────────────────────────────────────────────────

/**
 * Compute how many days (ceiling) until this problem reaches the darkRed threshold.
 *
 * @param {Object} problem
 * @returns {number} Infinity | 0 | positive integer (Math.ceil)
 */
export function calculateDaysUntilFlashing(problem) {
  if (!problem.solved) return Infinity;
  const result = calculateAwarenessScore(problem);
  if (result.score < 0) return Infinity;
  const config = getConfig();
  if (result.score >= config.thresholds.darkRed) return 0;
  const commitmentFactor = getCommitmentFactor();
  const tierDiffMultiplier = getTierDifficultyMultiplier(problem);
  const solvedFactor = getSolvedFactor(problem);
  const dailyRate = config.baseRate * commitmentFactor * tierDiffMultiplier / solvedFactor;
  if (dailyRate <= 0) return Infinity;
  const daysNeeded = (config.thresholds.darkRed - result.score) / dailyRate;
  return Math.ceil(daysNeeded);
}

// ── applyUrgentReviewFilter ───────────────────────────────────────────────────

/**
 * Filter rows to show only the most urgently-due solved problems.
 * Returns null with no DOM changes if no solved problems exist.
 *
 * Injectable deps version for testing:
 * @param {string} fileKey
 * @param {Object} deps
 * @param {Array} deps.problems - Problem array for this fileKey
 * @param {Array} deps.rows - Row objects with style.display and dataset.index
 * @param {Object|null} deps.statusEl - Element with .textContent for status message
 * @returns {{ minDays: number, urgentIndices: Set<number> }|null} null if no solved problems
 */
export function applyUrgentReviewFilter(fileKey, { problems, rows, statusEl }) {
  const solvedProblems = problems
    .map((problem, idx) => ({ idx, days: calculateDaysUntilFlashing(problem) }))
    .filter(item => item.days !== Infinity);

  if (solvedProblems.length === 0) return null;

  const minDays = Math.min(...solvedProblems.map(item => item.days));
  const urgentIndices = new Set(
    solvedProblems.filter(item => item.days === minDays).map(item => item.idx)
  );

  rows.forEach(row => {
    const idx = parseInt(row.dataset.index, 10);
    row.style.display = urgentIndices.has(idx) ? '' : 'none';
  });

  if (statusEl) {
    const count = urgentIndices.size;
    const msg = minDays === 0
      ? `${count} problem(s) flashing NOW`
      : `${count} problem(s) flashing in ${minDays} day(s)`;
    statusEl.textContent = msg;
  }

  return { minDays, urgentIndices };
}

// ── updateUrgentBtnState ──────────────────────────────────────────────────────

/**
 * Enable or disable the urgent-review button based on whether any problems are solved.
 *
 * @param {string} fileKey
 * @param {Object} deps
 * @param {Array} deps.problems - Problem array for this fileKey
 * @param {Object|null} deps.btn - Button element with .disabled property
 */
export function updateUrgentBtnState(fileKey, { problems, btn }) {
  if (!btn) return;
  const hasSolved = problems.some(p => p.solved);
  btn.disabled = !hasSolved;
}
